# This is a GitHub actions workflow for NCEPLIBS-g2.
#
# This builds and tests, then builds and tests the grib_util develop
# branch.
#
# Ed Hartnett, 5/25/23
name: grib_utils 
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

# Cancel in-progress workflows when pushing to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  grib_utils:
    runs-on: ubuntu-latest
    env:
      FC: gfortran
      CC: gcc

    strategy:
      matrix:
        grib_util-branch: [ejh_fix]
        jasper-version: [2.0.33, 3.0.5, 4.0.0]

    steps:

    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libpng-dev zlib1g-dev libjpeg-dev

    - name: "Build dependencies"
      uses: NOAA-EMC/ci-build-nceplibs@develop
      with:
        bacio-version: develop
        g2c-develop: develop
        ip-version: develop
        jasper-version: version-${{ matrix.jasper-version }}
        sp-version: develop
        w3emc-version: develop
        w3emc-cmake-args: -DBUILD_WITH_BUFR=OFF
        
    - name: checkout
      uses: actions/checkout@v4
      with:
        path: g2

    - name:  build
      run: |
        set -x
        cd g2
        mkdir build
        cd build
        cmake -DJasper_ROOT=$GITHUB_WORKSPACE/nceplibs/jasper -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-bacio;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-w3emc" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=~/g2 ..
        make -j2 VERBOSE=1
        make install

    - name: test
      run: |
        cd $GITHUB_WORKSPACE/g2/build
        ctest --verbose --output-on-failure --rerun-failed

    - name: checkout-grib_utils
      uses: actions/checkout@v4
      with: 
        repository: NOAA-EMC/NCEPLIBS-grib_util
        path: grib_utils
        ref: ${{ matrix.grib_util-branch }}
        
    - name: build-grib_utils
      run: |
        cd grib_utils
        mkdir build && cd build
        ls -l ~/jasper/lib
        export LD_LIBRARY_PATH=/home/runner/jasper/lib
        export PATH="~/g2c/bin:$PATH"
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="~/bacio;~/jasper;~/sp;~/ip;~/w3emc;~/g2;~/g2c" ..
-DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-bacio;$GITHUB_WORKSPACE/nceplibs/jasper;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-sp;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-ip;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-w3emc;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-g2;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-g2c"
        make -j2 VERBOSE=1
        ctest --output-on-failure --rerun-failed --verbose



