# This is a GitHub actions workflow for NCEPLIBS-g2.
#
# This builds the develop branch and does a memcheck with valgrind.
#
# Ed Hartnett, 5/16/24
name: memcheck
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

# Cancel in-progress workflows when pushing to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  memcheck:
    runs-on: ubuntu-latest
    env:
      FC: gfortran
      CC: gcc

    steps:

    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libpng-dev zlib1g-dev libjpeg-dev doxygen gcovr valgrind

    - name: checkout-bacio
      uses: actions/checkout@v4
      with:
        repository: NOAA-EMC/NCEPLIBS-bacio
        path: bacio
        ref: develop

    - name: build-bacio
      run: |
        cd bacio
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/bacio
        make -j2
        make install

    - name: checkout-w3emc
      uses: actions/checkout@v4
      with:
        repository: NOAA-EMC/NCEPLIBS-w3emc
        path: w3emc
        ref: develop

    - name: build-w3emc
      run: |
        cd w3emc
        mkdir build
        cd build
        cmake -DCMAKE_PREFIX_PATH=~/bacio -DCMAKE_INSTALL_PREFIX=~/w3emc -DBUILD_WITH_BUFR=OFF ..
        make -j2
        make install

    - name: cache-jasper
      id: cache-jasper
      uses: actions/cache@v4
      with:
        path: ~/Jasper
        key: jasper-${{ runner.os }}-4.0.0

    - name: checkout-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: jasper-software/jasper
        path: jasper
        ref: version-4.0.0

    - name: build-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'
      run: |
        cd jasper
        mkdir build-jasper && cd build-jasper
        cmake .. -DCMAKE_INSTALL_PREFIX=~/Jasper
        make -j2
        make install

    - name: checkout-ip
      uses: actions/checkout@v3
      with:
        repository: NOAA-EMC/NCEPLIBS-ip
        path: ip
        ref: develop
    
    - name: build-ip
      run: |
        cd ip
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=~/ip ..
        make -j2
        make install        

    - name: checkout
      uses: actions/checkout@v4
      with:
        path: g2

    - name: cache-data
      id: cache-data
      uses: actions/cache@v4
      with:
        path: ~/data
        key: data-memcheck-1

    - name: memcheck
      run: |
        cd g2
        mkdir build
        cd build
        cmake -DJasper_ROOT=~/Jasper -DCMAKE_PREFIX_PATH="~/bacio;~/w3emc;~/ip" -DCMAKE_Fortran_FLAGS="-g -O0" -DCMAKE_C_FLAGS="-g -O0" -DFTP_TEST_FILES=ON -DTEST_FILE_DIR=/home/runner/data -DCMAKE_BUILD_TYPE=Debug ..
        make -j2 VERBOSE=1

    - name: test_memcheck
      run: |
        cd $GITHUB_WORKSPACE/g2/build        
        ctest -LE "^noMemcheck$" -T memcheck

    - name: cache-data
      if: steps.cache-data.outputs.cache-hit != 'true'
      run: |
        mkdir ~/data
        cp $GITHUB_WORKSPACE/g2/build/tests/data/* ~/data


